services:
  front:
    image: ghcr.io/${OWNER:-cpe-4irc-eyjafjallajokull}/app-terrain-front:${IMAGE_TAG:-latest}
    container_name: app-terrain-front
    environment:
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST:-true}
      - API_URL=${API_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-terrain-front.rule=Host(`${FRONT_HOST}`)"
      - "traefik.http.routers.app-terrain-front.entrypoints=websecure"
      - "traefik.http.routers.app-terrain-front.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-terrain-front.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
